name: skillseed_app
description: SkillSeed - Ultra Advanced Soft Skills Platform (Flutter, SQLite offline-first; Firebase-ready)
publish_to: "none"
version: 0.3.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.2.0
  flutter_riverpod: ^2.5.1
  sqflite: ^2.3.3
  path: ^1.9.0
  url_launcher: ^6.3.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  uuid: ^4.5.1
  sqflite_common_ffi: ^2.3.2
  sqflite_common_ffi_web: ^0.4.4
  google_fonts: ^6.2.1
  animations: ^2.0.11
  flutter_animate: ^4.5.0
  lottie: ^3.1.2
  file_picker: ^8.0.3
  crypto: ^3.0.3
  share_plus: ^10.0.2
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_messaging: ^16.0.0
  firebase_app_check: ^0.4.0
  app_links: ^6.4.1

  # Firebase-ready (optional)
  # firebase_core: ^3.0.0
  # firebase_auth: ^5.1.0
  # cloud_firestore: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/
