// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOwFz6PWUd0gczC2iBT5NURUZH1XfKgFM',
    appId: '1:747241245521:web:5c079705cf32a62ef3e170',
    messagingSenderId: '747241245521',
    projectId: 'skillseed-be957',
    authDomain: 'skillseed-be957.firebaseapp.com',
    databaseURL: 'https://skillseed-be957-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skillseed-be957.firebasestorage.app',
    measurementId: 'G-ZTFN2MZPL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU7c_4B5yYd4ANni63h81RoNR7Bx1puDY',
    appId: '1:747241245521:android:2a3264b5770afc79f3e170',
    messagingSenderId: '747241245521',
    projectId: 'skillseed-be957',
    databaseURL: 'https://skillseed-be957-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skillseed-be957.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGPXm4KYqHIZBOAJlUG1lvs1UUolyUHjc',
    appId: '1:747241245521:ios:7a1ef81bf9893a95f3e170',
    messagingSenderId: '747241245521',
    projectId: 'skillseed-be957',
    databaseURL: 'https://skillseed-be957-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skillseed-be957.firebasestorage.app',
    iosBundleId: 'com.example.skillseedApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGPXm4KYqHIZBOAJlUG1lvs1UUolyUHjc',
    appId: '1:747241245521:ios:7a1ef81bf9893a95f3e170',
    messagingSenderId: '747241245521',
    projectId: 'skillseed-be957',
    databaseURL: 'https://skillseed-be957-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skillseed-be957.firebasestorage.app',
    iosBundleId: 'com.example.skillseedApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOwFz6PWUd0gczC2iBT5NURUZH1XfKgFM',
    appId: '1:747241245521:web:2fe84ee5e9fad432f3e170',
    messagingSenderId: '747241245521',
    projectId: 'skillseed-be957',
    authDomain: 'skillseed-be957.firebaseapp.com',
    databaseURL: 'https://skillseed-be957-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skillseed-be957.firebasestorage.app',
    measurementId: 'G-CBRN509X4W',
  );
}
